name: First GitHub Action

on:
  push:
    branches:
      - main
      - flow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "GitHub Actions workflow is running successfully!"